spring:
  application:
    name: concurso-ninja
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/concurso-ninja-db?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    show-sql: true
    open-in-view: false

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG